### ISSUE TITLE
converter doesn't write oggvorsis tags to opus file

### ISSUE THREAD

**Issue by elnull** [DeaDBeeF-Player/deadbeef#2001]
### Steps to reproduce the problem

Convert any file to opus format.

### What's going on? Describe the problem in as much detail as possible.

Output in log window:
converter: Failed to write ogg metadata to /tmp/opus/1-01.opus

### Information about the software:

Deadbeef version: git snapshot from 2018-04-08 e0f03a6
OS: Ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment]
What kind of opus encoder preset are you using? The built-in one, or another one? I just tried converting with the built-in one, and conversion + tagging completed successfully.

**Comment by elnull** [comment]
The one that comes in Ubuntu 18.04:
Package: opus-tools
Version: 0.1.10-1

**Comment by Alexey-Yakovenko** [comment]
I mean the preset in deadbeef itself

![image](https://user-images.githubusercontent.com/1895698/38467073-57006590-3b33-11e8-89b6-f2a5b6185cd5.png)

**Comment by elnull** [comment]
![de](https://user-images.githubusercontent.com/169721/38467108-7cc0c51e-3b3c-11e8-9556-6b0c1166d26c.png)
![screenshot-20180408_145333_zbjutv](https://user-images.githubusercontent.com/169721/38467121-a468d340-3b3c-11e8-83f2-4b79232d4404.png)

**Comment by Alexey-Yakovenko** [comment]
Ok.. Does it still happen if you change the output folder to anything else than /tmp?

**Comment by elnull** [comment]
No. Writing to $HOME leads to same result.

**Comment by Alexey-Yakovenko** [comment]
Ok.. something is fishy on linux then. I'll check it out.

**Comment by Alexey-Yakovenko** [comment]
I'm still not getting this problem. Works fine on linux.
Are you running travis build, or compiling on your machine?

**Comment by elnull** [comment]
It's my own build.

**Comment by Alexey-Yakovenko** [comment]
Then the easiest is to try the travis build, and if it works -- find out what kind of thing you forgot when you compiled your own build.

**Comment by elnull** [comment]
Travis build works fine. Trying to find what may be missing on my system.

**Comment by elnull** [comment]
It seems that libopusfile-dev was not installed.

**Comment by Alexey-Yakovenko** [comment]
cool, I guess it is solved then

**Comment by Samueru-sama** [comment]
I have the same problem when trying to convert to Opus, unfortunately in my case I use arch linux and I cannot find any package name libopusfile-dev, I do have opus and opus-tools instead, deadbeef is the deadbeef-git version from the Aur, any help?

**Comment by Oleksiy-Yakovenko** [comment]
@Samueru-sama arch doesn't use the notion of -dev packages. You need the "opusfile" package.
https://archlinux.org/packages/community/x86_64/opusfile/

**Comment by Samueru-sama** [comment]
> @Samueru-sama arch doesn't use the notion of -dev packages. You need the "opusfile" package. https://archlinux.org/packages/community/x86_64/opusfile/

Hi, unfortunately that didn't work, I still get ''converter: Failed to write ogg metadata'' error.

I originally could not even play opus files in deadbeef, I had to go to the FFMPEG plugin in deadbeef and manually add "";opus"" to the end of it.

I also could not encode to Opus, I had to install Opus-tools to be able to do it.

Worth mentioning that I can encode to Vorbis by just using the built in Vorbis option, and it even transfers the tags and album artwork without issue, the problem is with Opus, maybe something else is still missing.

**Comment by Oleksiy-Yakovenko** [comment]
The Converter requires a working native opus plugin (not ffmpeg) for writing tags.
Opus plugin requires libopusfile, libopus and libogg.
You can see whether the plugin was built by looking at the configure log, somewhere at the beginning of build log.

**Comment by Samueru-sama** [comment]
> The Converter requires a working native opus plugin (not ffmpeg) for writing tags. Opus plugin requires libopusfile, libopus and libogg. You can see whether the plugin was built by looking at the configure log, somewhere at the beginning of build log.

Finally, after reinstalling deadbeef the issue is now fixed, no idea why I didn't have the opus plugins at the beginning, thank you Oleksiy.

**Comment by Samueru-sama** [comment]
Spoke too soon, it almost works now, however album art does not get transferred to the new file 80% of the time, and it is also random, for example if I repeat a mass conversion then files that didn't get the album art before now have it while others won't. I tried reloading metadata and artwork in deadbeef with no luck.

**Comment by Oleksiy-Yakovenko** [comment]
I only recently added support for READING embedded album art from OGG files.
I did not implement writing album art yet to OGG files yet.

**Comment by Samueru-sama** [comment]
> I only recently added support for READING embedded album art from OGG files. I did not implement writing album art to OGG files yet.

Alright, I think that it was some cached album art conflict because I noticed that using refresh cover art removed the cover art that was showing for some of the converted files.

**Comment by samuelawachie** [comment]
> I only recently added support for READING embedded album art from OGG files. I did not implement writing album art to OGG files yet.

I added .opus files with embedded album art (as front cover). I embedded the art using Foobar. They show up in foober, in Neutron player and every other media player I have. But they don't show up in DeadBeef. I tried to install the opus plugin but found it much too difficult getting past the error "opus.c:35:10: fatal error: opus/opusfile.h: No such file or directory".
I don't know what to do anymore.

**Comment by Oleksiy-Yakovenko** [comment]
> I tried to install the opus plugin but found it much too difficult getting past the error "opus.c:35:10: fatal error: opus/opusfile.h: No such file or directory".
I don't know what to do anymore.

It sounds like you found the reason why album art is not loading from opus file. If you don't have this plugin (which is actually part of deadbeef build) -- they would not load, since it is this plugin that performs the job.

**Comment by samuelawachie** [comment]
> > I tried to install the opus plugin but found it much too difficult getting past the error "opus.c:35:10: fatal error: opus/opusfile.h: No such file or directory".
> > I don't know what to do anymore.
> 
> It sounds like you found the reason why album art is not loading from opus file. If you don't have this plugin (which is actually part of deadbeef build) -- they would not load, since it is this plugin that performs the job.

Oh dear.. I only twice installed a plugin on deadbeef (infobar and lyric plugin), and the lyrics plugin doesn't read from a location which is how I store my lyrics rather than embedded in lyric tag. When I installed them, I remember it being so difficult to make the file and install it. I can't even remember how I managed it at the end as I was new to Linux at the time. I went to look through my bash history, and could piece pieces of info together, but I couldn't get this opus plugin to install. 
I downloaded it from here (https://bitbucket.org/Lithopsian/deadbeef-opus/downloads/) but don't know how to get it installed. Could you show me how please? Just a step by step of making the file, after putting it in ~/.local/lib/deadbeef
I'll say I can certainly find my way around now on Linux, and with a little guidance should be able to get this working.

**Comment by Oleksiy-Yakovenko** [comment]
I think you misunderstood. Opus plugin comes preinstalled with deadbeef. If you download the official build -- it is included.
The plugin at bitbucket link would not work for you, it's not the one I was referring to.

**Comment by Oleksiy-Yakovenko** [comment]
> Just a step by step

1. download deadbeef from here https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.6/deadbeef-static_1.9.6-1_x86_64.tar.bz2/download
2. unpack
3. run
4. done

**Comment by samuelawachie** [comment]
> I think you misunderstood. Opus plugin comes preinstalled with deadbeef. If you download the official build -- it is included.
> The plugin at bitbucket link would not work for you, it's not the one I was referring to.

Well, if it’s for the “opus plug-in”, I’ve had that from the start, without which I would’ve not been able to play any .opus files I suppose. What I’m talking about is that when playing those files, their album art embedded as all my other songs are, don’t show up as those of the other file formats do. It’s just the turntable placeholder that shows as the art. I thought that plug-in at the site I linked could solve that issue. That’s the issue I’m trying to solve.

**Comment by Oleksiy-Yakovenko** [comment]
@samuelawachie can you run deadbeef from console, and post a startup log?

**Comment by samuelawachie** [comment]
> @samuelawachie can you run deadbeef from console, and post a startup log?

[Uploading deadbeeflog.txt…]()

**Comment by Oleksiy-Yakovenko** [comment]
Ok, you do have the bundled opus plugin, and you're running official build. This is good.

You also have another plugin installed in .local/lib/deadbeef, but it's ignored since it's built for another CPU architecture.
You should delete this one.

So what you're describing seems to be a legit bug, and your should create a new issue about it.
