### ISSUE TITLE
Lots of traslations have already been translated in transifex, but they have not been applied.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2207]
### Steps to reproduce the problem
Search the translation in transifex.
### What's going on? Describe the problem in as much detail as possible.
They have been translated long time ago, but they have never been applied to deadbeef.
### Information about the software:

Deadbeef version:deadbeef-git
OS:Manjaro Linux

**Comment by Alexey-Yakovenko** [comment]
Translations are applied to releases, but not to the development versions.

**Comment by laichiaheng** [comment]
It displays as <br> in the release version.
![2019-09-04 23-22-57 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64268602-f7a85d00-cf6a-11e9-803f-1f4342ca880f.png)

**Comment by Alexey-Yakovenko** [comment]
Well this means something is wrong with the translation

**Comment by Alexey-Yakovenko** [comment]
It's all volunteer-driven and unverified, I can't do much about that. If you can fix it - please do. Then it will be included in the next release.

**Comment by laichiaheng** [comment]
Done!
Do they need to be reviewed?

**Comment by Alexey-Yakovenko** [comment]
no, I don't think so

**Comment by Alexey-Yakovenko** [comment]
Which language is this? I want to verify that there are no problems

**Comment by Alexey-Yakovenko** [comment]
Ok this is weird, the strings are fixed in transifex indeed, but they aren't getting downloaded when I sync. I think it has to do with the review flag. I will try to disable this.

**Comment by Alexey-Yakovenko** [comment]
I looked more carefully in transifex.
This is what I see for the suspects:

 
![image](https://user-images.githubusercontent.com/1895698/64271586-dbda9200-cf3d-11e9-8ad2-a0d19bafe092.png)

This is where <br> comes from. So it's still not fixed.

**Comment by Alexey-Yakovenko** [comment]
Translations do correspond to what they are in transifex, therefore closing.

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko Done! Who place a `1` there?

**Comment by Alexey-Yakovenko** [comment]
I don't know. I'm not following translations. As I said before it's a completely volunteer driven effort. I only update translations shortly before releasing.

**Comment by laichiaheng** [comment]
@Alexey-Yakovenko Would you release a new version of DeaDBeeF in the near future? Lots of translations have been fixed and updated.

**Comment by Alexey-Yakovenko** [comment]
I will see what can be done.
