### ISSUE TITLE
Playlist text missing!

### ISSUE THREAD

**Issue by minuxlintebiandedition** [DeaDBeeF-Player/deadbeef#2781]
Everything else seems to be present and working, just no text in playlist columns, on 64 bit lmde4, happened after an upgrade to WebKit and a few other things. 
Same versions, 1.8.x working on other system on lmde5 but upgrade didn't fix the problem.
Not critical, interesting though.

**Comment by Alexey-Yakovenko** [comment]
@minuxlintebiandedition I believe this bug has been fixed in the 1.9.0-rc1 already, could you please try it out?
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9/deadbeef-static_1.9.0-rc1-1_x86_64.tar.bz2/download

**Comment by minuxlintebiandedition** [comment]
Sorry coming to this late, link is broken.
Would I need to compile that myself? Have no clue how to do that.
Where can I get this 1.9 RC?

**Comment by Alexey-Yakovenko** [comment]
@minuxlintebiandedition 1.9 series has shipped, and therefore you should try the latest version:
https://deadbeef.sourceforge.io/download.html

**Comment by minuxlintebiandedition** [comment]
Got it, but the playlist text is still missing
![image](https://user-images.githubusercontent.com/42706563/170843422-9d9d4ad2-01d2-4398-9292-4a73af09d558.png)

**Comment by Alexey-Yakovenko** [comment]
ok, this is different from what I thought -- and I have never seen this problem before.

could you please file a new issue, and this time fill out the form with the information how to reproduce this?

**Comment by Alexey-Yakovenko** [comment]
Please remember to include the relevant things -- such as the linux distribution, desktop environment, and very precise versions of everything. The more relevant information you provide -- the less likely your issue would be closed as "can't reproduce".

**Comment by minuxlintebiandedition** [comment]
Changed odd and even to different colours in playlist, resizing window makes it all go back to 1 colour.
Looking at deadbeef 1.8.1 on the same machine, booting into the same version of lmde5 Elsie, not reproduced.

Will investigate further, have no idea how to run in debug, step thru code, core dump, stack trace etc but will try. DB is my favourite Linux app so a good place to learn :)
