### ISSUE TITLE
Applying metadata breaks .mp4 files

### ISSUE THREAD

**Issue by Paculino** [DeaDBeeF-Player/deadbeef#3261]
Hello, I am using the MX-repo 1.9.5-3~mx23+1 version of deadbeef, with all defaults and using gtk3. I have noticed that while I can load mp4 (and m4a) files fine with deadbeef, but if I go into properties and edit metadata, or simply hit 'apply' (without making any edit), the file breaks, although remaining available to open with deadbeef. Only deadbeef can open it though; ffprobe fails as do video players. The codec is aac with filetype mp4 aac according to properties, both before and after this problem. Ffprobe and ffmpeg both report 'invalid data found when processing input', while mpv and celluloid simply say that the file format is unrecognized. mp4 is in the list of filetypes chosen for use with the ffmpeg plugin, if relevant. So far the only workaround I have found is to copy the file and separate the audio stream for use with deadbeef alone.

**Comment by Oleksiy-Yakovenko** [comment]
I'm fairly sure that this problem existed some years ago, and it has been fixed.
Please update to latest.

**Comment by Paculino** [comment]
Is there a way to fix the files, by any chance? That is my main concern.

**Comment by Oleksiy-Yakovenko** [comment]
TBH I'm not sure. It's been almost 3 years since this bug got fixed, and I don't even remember the details.
Maybe just try to reopen those same files in new version of deadbeef, and re-save the tags?

**Comment by Paculino** [comment]
In case anyone else finds this later, reopening/reapply metadata does not fix the mp4 files, so you just have to redownload them.
